### ISSUE TITLE
no open in my win10. only 0.1secons logo down

### ISSUE THREAD

**Issue by sontoriyama** [GewoonJaap/WinWhisper#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GewoonJaap** [comment]
Could you open the command prompt, drag the winwhisper.exe into it and press enter, and send me the error that appears? I think you need to install .net 7.0.. But the error can verify it
