### ISSUE TITLE
not transcribe spanish video to spanish srt file

### ISSUE THREAD

**Issue by johnfelipe** [GewoonJaap/WinWhisper#14]
Welcome to WinWhisper (1.3.2.0). Generate subtitles with ease using WhisperAI.
	Enter the path where you want the subtitles to be saved...
	Leave empty to save the subtitles in the ./Subtitles folder

	Enter the video path or the folder path that contains the videos you want to process...
	"d:\Users\GAMEMAX\Downloads\Capacitacion sprint2 datalake daniel-20231121_112907-Grabación de la reunión.mp4"
	In which language code (en,nl etc) is the audio for video: Capacitacion sprint2 datalake daniel-20231121_112907-Grabación de la reunión.mp4? Leave empty to auto detect
	es
	Do you want to translate the subtitles to English? (yes/no) Default: no
	no
	Processing video: Capacitacion sprint2 datalake daniel-20231121_112907-Grabación de la reunión.mp4
	Extracting audio from video file located at: d:\Users\GAMEMAX\Downloads\Capacitacion sprint2 datalake daniel-20231121_112907-Grabación de la reunión.mp4
	This might take a while depending on the file size and drive speed...
	Extracted audio from video, RawAudio/Capacitacion sprint2 datalake daniel-20231121_112907-Grabación de la reunión.wav
	Downloading Whisper AI model ggml-base.bin. This might take a while depending on your internet speed..
	The application might exit after downloading. Please restart the application manually in that case!
	Downloaded model
	Processing audio file
	CSSS 00:00:00,000 ==> 00:00:04,000 :  [Música]
	CSSS 00:00:04,000 ==> 00:00:08,000 :  [Música]
	CSSS 00:00:08,000 ==> 00:00:12,000 :  [Música]
	CSSS 00:00:12,000 ==> 00:00:16,000 :  [Música]
	CSSS 00:00:16,000 ==> 00:00:20,000 :  [Música]
	CSSS 00:00:20,000 ==> 00:00:24,000 :  [Música]
	CSSS 00:00:24,000 ==> 00:00:28,000 :  [Música]
	CSSS 00:00:28,000 ==> 00:00:32,000 :  [Música]
	CSSS 00:00:32,000 ==> 00:00:36,000 :  [Música]
	CSSS 00:00:36,000 ==> 00:00:40,000 :  [Música]
	CSSS 00:00:40,000 ==> 00:00:44,000 :  [Música]
	CSSS 00:00:44,000 ==> 00:00:48,000 :  [Música]
	CSSS 00:00:48,000 ==> 00:00:52,000 :  [Música]
	CSSS 00:00:52,000 ==> 00:00:56,000 :  [Música]
	CSSS 00:00:56,000 ==> 00:01:00,000 :  [Música]
	CSSS 00:01:00,000 ==> 00:01:04,000 :  [Música]
	CSSS 00:01:04,000 ==> 00:01:08,000 :  [Música]
	CSSS 00:01:08,000 ==> 00:01:12,000 :  [Música]
	CSSS 00:01:12,000 ==> 00:01:16,000 :  [Música]
	CSSS 00:01:16,000 ==> 00:01:20,000 :  [Música]
	CSSS 00:01:20,000 ==> 00:01:24,000 :  [Música]
	CSSS 00:01:24,000 ==> 00:01:28,000 :  [Música]
	CSSS 00:01:28,000 ==> 00:01:32,000 :  [Música]
	CSSS 00:01:32,000 ==> 00:01:36,000 :  [Música]
	CSSS 00:01:36,000 ==> 00:01:40,000 :  [Música]
	CSSS 00:01:40,000 ==> 00:01:44,000 :  [Música]
	CSSS 00:01:44,000 ==> 00:01:48,000 :  [Música]
	CSSS 00:01:48,000 ==> 00:01:52,000 :  [Música]
	CSSS 00:01:52,000 ==> 00:01:56,000 :  [Música]
	CSSS 00:01:56,000 ==> 00:02:00,000 :  [Música]
	CSSS 00:02:00,000 ==> 00:02:04,000 :  [Música]
	CSSS 00:02:04,000 ==> 00:02:08,000 :  [Música]
	CSSS 00:02:08,000 ==> 00:02:12,000 :  [Música]
	CSSS 00:02:12,000 ==> 00:02:16,000 :  [Música]
	CSSS 00:02:16,000 ==> 00:02:20,000 :  [Música]
	CSSS 00:02:20,000 ==> 00:02:24,000 :  [Música]
	CSSS 00:02:24,000 ==> 00:02:28,000 :  [Música]
	CSSS 00:02:28,000 ==> 00:02:32,000 :  [Música]
	CSSS 00:02:32,000 ==> 00:02:36,000 :  [Música]
	CSSS 00:02:36,000 ==> 00:02:40,000 :  [Música]
	CSSS 00:02:40,000 ==> 00:02:44,000 :  [Música]
	CSSS 00:02:44,000 ==> 00:02:48,000 :  [Música]

**Comment by GewoonJaap** [comment]
Hi John,
Am sorry to hear that :( by any chance you could give me the video for debugging purposes? Feel free to email it to me: winwhisper@mrproper.dev

Feel free to convert the video to a MP3 (https://convertio.co/nl/mp4-mp3/) if you want to leave out the video for privacy reasons :)

**Comment by johnfelipe** [comment]
uploading to send video with google drive

**Comment by dophuchoan** [comment]
Please include the faster_Whisper_model_large model v2 in the selection. It's perfect to use! )

**Comment by GewoonJaap** [comment]
What would be the optimal selection flow. Select per video (Since you can enter a folder path this might lead to alot of the same choices) or more per "session", so when you open WinWhisper/input a new path.

**Comment by JustAndreww** [comment]
Yep, agree. Per session is more than enough.
