### ISSUE TITLE
Illegal Instruction Error

### ISSUE THREAD

**Issue by joesixpack** [GewoonJaap/WinWhisper#15]
Windows 11. Have both regular and desktop NET 7 installed.  Occurs in either standalone or installer.  Happens after extracting the audio file:

![image](https://github.com/GewoonJaap/WinWhisper/assets/23145642/58e4e131-6207-456a-b4aa-81988e18d881)

**Comment by joesixpack** [comment]
![image](https://github.com/GewoonJaap/WinWhisper/assets/23145642/1979fefd-526b-432f-a57e-b74948fb8969)

**Comment by joesixpack** [comment]
Occurs with .NET runtime 7.0.18 or 7.0.12 and also in Windows 10 LTSC.

**Comment by GewoonJaap** [comment]
Hmmf strange issue we got here. When does issue happen? Has it already downloaded the winwhisper model? (This is only done once) Does it also happen on every video file or only specific ones?

**Comment by GewoonJaap** [comment]
Also which CPU do you have? WinWhisper requires your CPU to support the AVX/AVX2 instruction set. Is your CPU compatible with this?
