### ISSUE TITLE
Does not work with Chinese language

### ISSUE THREAD

**Issue by flyke** [GewoonJaap/WinWhisper#2]
**Describe the bug**
No translations when video source language is Chinese

**Screenshots**
![image](https://github.com/GewoonJaap/WinWhisper/assets/9461338/ec16572f-2b6d-4ad0-951e-11d8ed163529)

**Comment by flyke** [comment]
automatic language detection did not work, entering 'zh' as language code (I searched Google for official language code chinese) did not work, but entering 'cn' as language did yield other results than questionmarks, alhough nothing actually sensible.
![image](https://github.com/GewoonJaap/WinWhisper/assets/9461338/65abc76d-4e6e-44ff-b144-bfa89100f364)
after that 'interesting' bit everything is always the same.
![image](https://github.com/GewoonJaap/WinWhisper/assets/9461338/e2897e42-0440-4b47-8383-0bac74b1230f)

**Comment by GewoonJaap** [comment]
Oh okay, I am surprised it did actually work. Since this application uses the base model, I thought I simply had to switch to a bigger one which supports more languages. But I am glad it works :)

**Comment by flyke** [comment]
Well I don't know chinese myself, so I cannot attest how well it works, thats's why I opened a feature request to be able to also translate. At first glance, it does indeed seem to extract chinese from the source. At second glance, just from this screenshot, I see some repeated (chinese) text: See line 3, 7, 11, 15, 19 but also 23, 27, 71, 75.
So that could indicate it is not working well. But can only verify if this thing could translate.
