### ISSUE TITLE
Support for other Whisper models

### ISSUE THREAD

**Issue by JohnstonJ** [GewoonJaap/WinWhisper#22]
**Is your feature request related to a problem? Please describe.**

I would like to be able to try alternative models for use with Whisper.  Larger models might provide better results.

**Describe the solution you'd like**

Alternative tools like https://github.com/m1guelpf/auto-subtitle?tab=readme-ov-file#usage offer a `--model` parameter or similar, which allows choosing alternative models for use with Whisper.

WinWhisper should also offer a parameter for choosing the model.

**Additional context**
It looks like WinWhisper has hard-coded the model to the `base` model.  This should be customizable: https://github.com/GewoonJaap/WinWhisper/blob/5a77de230f93e5abab8b54e33f2a7dd0206ce895/WhisperAI/AudioProcessor.cs#L10

**Comment by GewoonJaap** [comment]
Hi, thanks for the suggestion.
How would you like to see this configurable? For example on winwhisper startup it will ask for the model to use?

**Comment by JohnstonJ** [comment]
> Hi, thanks for the suggestion. How would you like to see this configurable? For example on winwhisper startup it will ask for the model to use?

The suggestion to ask for a model on startup is a great idea!

Of course, the exact experience for the user can be up to your design: however you think might be best.  The main point is there should be _some_ way to change the model...

**Comment by GewoonJaap** [comment]
Okay thank you! I think I will implement it like that, and maybe save the last used model so you can just hit enter and skip that startup script if you want to use the same model again. I hope to implement it this week(end)

**Comment by GewoonJaap** [comment]
Took a while but managed to find some time and implement it. Has been released today
