### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by flyke** [GewoonJaap/WinWhisper#3]
I would like to see an optional translation feature. So the code optionally asks for a translation language code. If given, it will translate the subtracted text to the desired language before saving it into the .srt file. So this could essentially generate Dutch subtitles for an English source video for example.

**Comment by flyke** [comment]
From the https://github.com/openai/whisper page itself:
_Adding --task translate will translate the speech into English:
`whisper japanese.wav --language Japanese --task translate`_

**Comment by GewoonJaap** [comment]
I guess the translate task always translates to english? I saw that the translate function is available in c#, but I can't set the destination language. I guess it defaults to english then

**Comment by JustAndreww** [comment]
At least something to play with :) Sometimes eng translation is more than enough.

**Comment by flyke** [comment]
So could you create a release that has the translate to english option ?

**Comment by GewoonJaap** [comment]
Will do today
