### ISSUE TITLE
Batch process

### ISSUE THREAD

**Issue by hirowa** [GewoonJaap/WinWhisper#4]
Hi there! Amazing app you have here!
I just wanted to know if there is a way I can batch process multiple files?
One after another.
By creating a list of file names, or maybe input a folder?

And maybe also add the option to save the .srt files directly in the source folder.

Hope you can help me, thanks.

**Comment by GewoonJaap** [comment]
Hi,
Thank you very much :) I think this would be possible.
So about the new flow, you can either drag and drop the file or the folder, then the application will detect if it is a folder or file.
In case of the file, the flow stays the same.
In case of a folder, it will check for .mp4, .mov etc files and use the existing file flow for each file in the folder.

**Comment by hirowa** [comment]
That would be awesome and super helpful, specially for TV shows with a large number of episodes.
Thanks for the reply!

**Comment by GewoonJaap** [comment]
I just started working on this flow: https://github.com/GewoonJaap/WinWhisper/tree/feature/batch-processing

At a quick glance it works. You enter the subtitle destination path, video or video folder path.
Then you can set the language for each video, and it will start processing :)

**Comment by GewoonJaap** [comment]
I will conduct some more testing later today/tomorrow and release it if it works as expected :)
